[build]
  publish = "dist/public"
  command = "npm install && npm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "development"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: API redirects if needed
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true
